### ISSUE TITLE
Rename to jupyter-resource-usage

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter-resource-usage#73]
Now that the repo has been moved to the `jupyter-server` organization (https://github.com/jupyter-server/team-compass/issues/3), we should be able to rename the Python package and other instances of `nbresuse` to `jupyter-resource-usage`.

And publish a new version on PyPI with the new name.

### TODO

- [x] Rename the `jupyter-resource-usage`
- [x] Publish to PyPI: https://pypi.org/project/jupyter-resource-usage/
- [x] Publish the lab extension to npm
- [x] Add new maintainers for the PyPI package
- [x] Document how to migrate to `0.5.0` in the changelog (and compatibility with JupyterLab 2 and 3)
- [x] Create new conda recipe: https://github.com/conda-forge/staged-recipes/pull/13508
- [x] Handle the renaming for the conda forge package: https://github.com/conda-forge/nbresuse-feedstock -> https://github.com/conda-forge/jupyter-resource-usage-feedstock
- [x] Update Binder

**Comment by manics** [comment]
If you're renaming the package this might be a good opportunity to make any breaking changes? e.g. following up from https://github.com/jupyter-server/jupyter-resource-usage/pull/68 `/metrics` could be completely removed instead of just deprecated?

**Comment by jtpio** [comment]
Good point.

And include the lab extension for JupyterLab 3: https://github.com/jupyter-server/jupyter-resource-usage/pull/69

So everything would work with the new endpoint with a single: `pip install jupyter-resource-usage`.

**Comment by jtpio** [comment]
To rename the project on PyPI, we can follow this: https://www.python.org/dev/peps/pep-0423/#how-to-rename-a-project

For conda, we can probably do something similar:

- create a new feedstock for `jupyter-resource-usage`
- make the current recipe only depend on the new package in https://github.com/conda-forge/nbresuse-feedstock

**Comment by jtpio** [comment]
Also, even though the name of the package changes, we can continue with `0.5.0` for the next version.

Which should make make things less confusing, especially when following the changelog.

**Comment by jtpio** [comment]
Since this repo lives in the `jupyter-server` organization, I just invited the same list of maintainers as for the `jupyter-server` package: https://pypi.org/project/jupyter-server/ + Yuvi.

Let me know if you would like to be added as a maintainer on PyPI.

**Comment by Jeffwan** [comment]
I am new to this area. What does it mean when this repo moved to `jupyter-server` org?  Will this repo ship with jupyter server together?

**Comment by jtpio** [comment]
Thanks and welcome @Jeffwan!

The move was done mostly to answer some questions about the maintainability of the project and its future. There are a couple of other projects using it, and some people willing to contribute to it.

There are also some answers in https://github.com/jupyter-server/team-compass/issues/3 and https://github.com/jupyter-server/jupyter-resource-usage/issues/62.

And the roadmap: https://github.com/jupyter-server/jupyter-resource-usage/issues/58
With some items talking about having metrics baked in Jupyter Server at some point in the future.

**Comment by jtpio** [comment]
yes!

**Comment by jtpio** [comment]
btw @krassowski and / or @echarles (or anyone interested) if you would like to be added as maintainer for the conda package, feel to open a PR on https://github.com/conda-forge/jupyter-resource-usage-feedstock. Thanks!
